# Generated by Django 3.1.5 on 2021-01-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_car', models.CharField(max_length=128, verbose_name='Марка автомобиля')),
                ('model_car', models.CharField(max_length=128, verbose_name='Модель автомобиля')),
                ('title_car', models.TextField(verbose_name='Об автомобиле')),
                ('price_car', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена автомобиля')),
                ('image_car', models.ImageField(upload_to='', verbose_name='Фото автомобиля')),
            ],
        ),
    ]
