# Generated by Django 3.1.5 on 2021-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=128, verbose_name='Адресс автосалона')),
                ('e_mail', models.EmailField(max_length=256, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_news', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('title_news', models.TextField(verbose_name='Текст новости')),
                ('create_news', models.DateTimeField(auto_now=True, verbose_name='Дата добавления новости')),
            ],
        ),
    ]
