# Generated by Django 3.1.5 on 2021-01-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_news',
            field=models.DateTimeField(verbose_name='Дата добавления новости'),
        ),
    ]
