# Generated by Django 3.1.5 on 2021-01-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210112_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand_car',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, verbose_name='Марка автомобиля'),
        ),
    ]
