# Generated by Django 3.1.5 on 2021-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210112_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand_car_af',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ar',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ar_dz',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ast',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_az',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_be',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_bg',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_bn',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_br',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_bs',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ca',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_cs',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_cy',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_da',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_de',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_dsb',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_el',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_en',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_en_au',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_en_gb',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_eo',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_es',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_es_ar',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_es_co',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_es_mx',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_es_ni',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_es_ve',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_et',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_eu',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_fa',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_fi',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_fr',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_fy',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ga',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_gd',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_gl',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_he',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_hi',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_hr',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_hsb',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_hu',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_hy',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ia',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ig',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ind',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_io',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_is',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_it',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ja',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ka',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_kab',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_kk',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_km',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_kn',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ko',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ky',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_lb',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_lt',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_lv',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_mk',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ml',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_mn',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_mr',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_my',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_nb',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ne',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_nl',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_nn',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_os',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_pa',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_pl',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_pt',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_pt_br',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ro',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ru',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_sk',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_sl',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_sq',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_sr',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_sr_latn',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_sv',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_sw',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ta',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_te',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_tg',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_th',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_tk',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_tr',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_tt',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_udm',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_uk',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_ur',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_uz',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_vi',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_zh_hans',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_car_zh_hant',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Bmw', 'Bmw'), ('Audi', 'Audi')], max_length=64, null=True, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_af',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ar',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ar_dz',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ast',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_az',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_be',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_bg',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_bn',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_br',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_bs',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ca',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_cs',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_cy',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_da',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_dsb',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_el',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_en_au',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_en_gb',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_eo',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_es',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_es_ar',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_es_co',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_es_mx',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_es_ni',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_es_ve',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_et',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_eu',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_fa',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_fi',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_fy',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ga',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_gd',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_gl',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_he',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_hi',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_hr',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_hsb',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_hu',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_hy',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ia',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ig',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ind',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_io',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_is',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_it',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ja',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ka',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_kab',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_km',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_kn',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ko',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ky',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_lb',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_lt',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_lv',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_mk',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ml',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_mn',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_mr',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_my',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_nb',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ne',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_nl',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_nn',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_os',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_pa',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_pl',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_pt',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_pt_br',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ro',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_sk',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_sl',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_sq',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_sr',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_sr_latn',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_sv',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_sw',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ta',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_te',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_tg',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_th',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_tk',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_tr',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_tt',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_udm',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_uk',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_ur',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_vi',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_zh_hans',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_car_zh_hant',
            field=models.CharField(max_length=128, null=True, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_af',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ar',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ar_dz',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ast',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_az',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_be',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_bg',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_bn',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_br',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_bs',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ca',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_cs',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_cy',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_da',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_de',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_dsb',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_el',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_en',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_en_au',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_en_gb',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_eo',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_es',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_es_ar',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_es_co',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_es_mx',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_es_ni',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_es_ve',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_et',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_eu',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_fa',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_fi',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_fr',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_fy',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ga',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_gd',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_gl',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_he',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_hi',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_hr',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_hsb',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_hu',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_hy',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ia',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ig',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ind',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_io',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_is',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_it',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ja',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ka',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_kab',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_kk',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_km',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_kn',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ko',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ky',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_lb',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_lt',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_lv',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_mk',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ml',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_mn',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_mr',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_my',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_nb',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ne',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_nl',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_nn',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_os',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_pa',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_pl',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_pt',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_pt_br',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ro',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ru',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_sk',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_sl',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_sq',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_sr',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_sr_latn',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_sv',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_sw',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ta',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_te',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_tg',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_th',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_tk',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_tr',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_tt',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_udm',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_uk',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ur',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_uz',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_vi',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_zh_hans',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_zh_hant',
            field=models.TextField(null=True, verbose_name='Об автомобиле'),
        ),
    ]
